version: '2'
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./.storage/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles
    notebook:
        image: jupyter/scipy-notebook:latest
        ports:
            - 8008:8888
        volumes:
            - ./analyzers/work:/home/jovyan/work
        command: jupyter notebook --NotebookApp.token='' --NotebookApp.password=''
